DECLARE a = "aa";

SELECT 'a', a;
SELECT 'a', a, COUNT(*);
SELECT 'a', a, COUNT(*) GROUP BY 1;
SELECT 'a' AS a, a;
SELECT 'a' AS a, a, COUNT(*);
SELECT 'a' AS a, a, COUNT(*) GROUP BY 1;

SELECT 'a', a FROM VALUES(1) AS t(a);
SELECT 'a', a, COUNT(*) FROM VALUES(1) AS t(a) GROUP BY ALL;
SELECT 'a' AS a, a FROM VALUES(1) AS t(a);
SELECT 'a' AS a, a, COUNT(*) FROM VALUES(1) AS t(a) GROUP BY ALL;

SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1', col1);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT col1 AS col1, col1);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1' AS col1, col1);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1' AS col1, col1, COUNT(*) GROUP BY 1);

SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1', col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1', col1, COUNT(*) FROM VALUES(1) GROUP BY ALL);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT col1 AS col1, col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT col1 AS col1, col1, COUNT(*) FROM VALUES(1) GROUP BY ALL);
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1' AS col1, col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) WHERE EXISTS (SELECT 'col1' AS col1, col1, COUNT(*) FROM VALUES(1) GROUP BY ALL);

SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1', col1);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT col1 AS col1, col1);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1' AS col1, col1);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1' AS col1, col1, COUNT(*) GROUP BY 1);

SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1', col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1', col1, COUNT(*) FROM VALUES(1) GROUP BY ALL);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT col1 AS col1, col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT col1 AS col1, col1, COUNT(*) FROM VALUES(1) GROUP BY ALL);
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1' AS col1, col1 FROM VALUES(1));
SELECT col1 FROM VALUES(1) GROUP BY col1 HAVING EXISTS (SELECT 'col1' AS col1, col1, COUNT(*) FROM VALUES(1) GROUP BY ALL);